"use client";

import { useTenantSuperadmin } from "@/app/context/superadmin_contexts/tenantSuperadmin";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export const TenantForm = () => {
  const {
    StatusBadge,
    formik,
    mode,
    handleCloseForm,
    handleAdd,
    handleEdit,
    handleView,
    selectedTenant,
    setSelectedTenant,
    listLoading,
    setListLoading,
    listingData,
    setListingData,
  } = useTenantSuperadmin();

  return (
    <section className="space-y-6">
      <div className="flex flex-col gap-4 rounded-[28px] border border-white/60 bg-white/60 p-5 shadow-[0_24px_80px_-48px_rgba(15,23,42,0.4)] backdrop-blur">
        <div>
          <h1 className="text-2xl leading-none tracking-tight font-display">
            {mode === "edit" ? "Edit Tenant" : "Add Tenant"}
          </h1>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">
            {mode === "edit"
              ? "Update tenant details and save changes."
              : "Create a new tenant workspace with validated details."}
          </p>
        </div>
      </div>

      <form className="space-y-4" onSubmit={formik.handleSubmit}>
        {/* Basic Info */}
        <Card className="overflow-hidden border-border/70 bg-white/70">
          <CardHeader className="py-2">
            <CardTitle className="text-md">Basic info</CardTitle>
            <CardDescription>Basic tenant details.</CardDescription>
          </CardHeader>
          <CardContent className="py-5">
            <div className="grid grid-cols-12 gap-4">
              <div className="col-span-12 md:col-span-6">
                <Input
                  name="companyName"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="Tenant name"
                  value={formik.values.companyName}
                  error={formik.errors.companyName}
                />
                {formik.touched.companyName && formik.errors.companyName && (
                  <p className="mt-1 text-xs text-red-600 ms-2">
                    {formik.errors.companyName}
                  </p>
                )}
              </div>

              <div className="col-span-12 md:col-span-6">
                <Input
                  name="slug"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="Slug"
                  value={formik.values.slug}
                  error={formik.errors.slug}
                />
                {formik.touched.slug && formik.errors.slug && (
                  <p className="mt-1 text-xs text-red-600 ms-2">
                    {formik.errors.slug}
                  </p>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Domain Info */}
        <Card className="overflow-hidden border-border/70 bg-white/70">
          <CardHeader className="py-2">
            <CardTitle className="text-md">Domain</CardTitle>
            <CardDescription>Provide the domain details.</CardDescription>
          </CardHeader>
          <CardContent className="py-5">
            <div className="grid grid-cols-12 gap-4">
              <div className="col-span-12 md:col-span-6">
                <Input
                  name="hostname"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="Domain name"
                  value={formik.values.hostname}
                  error={formik.errors.hostname}
                />
                {formik.touched.hostname && formik.errors.hostname && (
                  <p className="mt-1 text-xs text-red-600 ms-2">
                    {formik.errors.hostname}
                  </p>
                )}
              </div>

              <div className="col-span-12 md:col-span-6">
                <Input
                  name="owner_name"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="Owner name"
                  value={formik.values.owner_name}
                />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Database Info */}
        <Card className="overflow-hidden border-border/70 bg-white/70">
          <CardHeader className="py-2">
            <CardTitle className="text-md">
              Database <span className="text-xs">(Optional)</span>
            </CardTitle>
            <CardDescription>
              If don't have DB then automatically generated by system.
            </CardDescription>
          </CardHeader>
          <CardContent className="py-5">
            <div className="grid grid-cols-12 gap-4">
              <div className="col-span-12 md:col-span-6">
                <Input
                  name="dbName"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="Database name"
                  value={formik.values.dbName}
                />
              </div>

              <div className="col-span-12 md:col-span-6">
                <Input
                  name="dbHost"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="DB Host name"
                  value={formik.values.dbHost}
                />
              </div>

              <div className="col-span-12 md:col-span-6">
                <Input
                  name="dbPort"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="DB Port"
                  type="email"
                  value={formik.values.dbPort}
                />
              </div>

              <div className="col-span-12 md:col-span-6">
                <Input
                  name="dbUser"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="DB User Name"
                  value={formik.values.dbUser}
                />
              </div>

              <div className="col-span-6 md:col-span-6">
                <Input
                  name="dbPassword"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  placeholder="DB Password"
                  value={formik.values.dbPassword}
                />
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="flex justify-end gap-3">
          <Button onClick={handleCloseForm} type="button" variant="outline">
            Back to Listing
          </Button>
          <Button type="submit">
            {mode === "edit" ? "Update Tenant" : "Create Tenant"}
          </Button>
        </div>
      </form>
    </section>
  );
};
